server:
  port: 8081

spring:
  application:
    name: paperless
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paperless}
    username: ${SPRING_DATASOURCE_USERNAME:paperless}
    password: ${SPRING_DATASOURCE_PASSWORD:paperless}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

springdoc:
  swagger-ui:
    ui: /openapi.yaml
